### ISSUE TITLE
Code release?

### ISSUE THREAD

**Issue by robinsonkwame** [Frank-ZY-Dou/TORE#1]
Love this work! Wanted to follow up since the repository was made roughly 8 months ago. Hopefully this will be MIT or Apache licensed.

**Comment by Frank-ZY-Dou** [comment]
Hi~ Thank you very much for your interest in our work. Since we are still busy with the supplementary materials for CVPR24, we will release our code in the very near future. Thanks!

**Comment by Dariushuangg** [comment]
Nice work and thanks in advanced for the release :)
