### ISSUE TITLE
Checkpoint licensing

### ISSUE THREAD

**Issue by robinsonkwame** [Frank-ZY-Dou/TORE#2]
Just wanted to follow up on the licensing for the checkpoints, are they also MIT? I recognize that the SMPL and MANO models are NC scientific purposes only.

**Comment by Frank-ZY-Dou** [comment]
> Just wanted to follow up on the licensing for the checkpoints, are they also MIT? I recognize that the SMPL and MANO models are NC scientific purposes only.

Yes, SMPL and MANO models are for NC scientific purposes only. Our method part (the token reduction part) can be MIT.
